services:
  - type: web
    name: taximizerpro
    runtime: python
    rootDir: taxweb
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    envVars:
      - key: GOOGLEDRIVE_ACCESS_TOKEN
        sync: false
      - key: GMAIL_ACCESS_TOKEN
        sync: false
